import type { Metadata } from "next";
import { Geist, IM_Fell_English, UnifrakturMaguntia, Libre_Baskerville, Cormorant_Garamond } from 'next/font/google'

import "./globals.css";
import Navbar from "@/components/Navbar";


const geist = Geist({ 
  subsets: ['latin'],
  variable: '--font-geist'
})

const imFell = IM_Fell_English({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-im-fell'
})

const unifraktur = UnifrakturMaguntia({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-unifraktur'
})

const libre = Libre_Baskerville({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-libre'
})

const cormorant = Cormorant_Garamond({ 
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-cormorant'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${imFell.variable} ${unifraktur.variable} ${libre.variable} ${cormorant.variable}`}
      >
        <Navbar />
       <main className="pt-20"> {/* or pt-16, pt-24 depending on navbar height */}
          {children}
        </main>
      </body>
    </html>
  );
}
